#available options:
#indicator: type, period, candlePriceType, granularity
#### candlePriceType can have one of 5 values: OPEN, CLOSE, HIGH, LOW, MEDIUM
#### maType can have one of 3 values: SIMPLE, EXPONENTIAL, WEIGHTED
#### granularity can have one of : S5, S10, S15, S30, M1, M2, M4, M5, M10, M15, M30, H1, H2, H3, H4, H6, H8, H12, D, W, M;
# candlesQuantity have:
#### initial - initial number of candles for calculating indicators
#### update - number of candles when updating indicators after first initialization
# risk have: riskPerTrade - risk per trade as decimal example - 0.01 is 1% of the account
## Default values:
#candlesQuantity: initial: "4999", update: "2"
#risk: riskPerTrade: "0.01"
## For default values omit from the file

indicator1:
  type: "rsi"
  period: "14"
  candlePriceType: "CLOSE"
  granularity: "M30"
indicator2:
  position: "price"
  period: "1"
  candlePriceType: "CLOSE"
  granularity: "M30"
  type: "SIMPLE"
indicator3:
  position: "daily"
  period: "1"
  candlePriceType: "OPEN"
  granularity: "D"
  type: "SIMPLE"
indicator4:
  position: "fast"
  period: "5"
  candlePriceType: "CLOSE"
  granularity: "M30"
  type: "WEIGHTED"
indicator5:
  position: "middle"
  period: "20"
  candlePriceType: "CLOSE"
  granularity: "M30"
  type: "WEIGHTED"
indicator6:
  position: "slow"
  period: "100"
  candlePriceType: "CLOSE"
  granularity: "M30"
  type: "WEIGHTED"
candlesQuantity:
  initial: "4999"
  update: "2"
risk:
  riskPerTrade: "0.01"
entry:
  entryStrategy: "standard"
order:
  orderStrategy: "standard"
exit:
  exitStrategy: "fullClose"